name: 'Repos Dependency Update Action'
description: 'Update .repos file to match base or head branch'
author: 'Luis Camero'
inputs:
  branch:
    description: 'Branch to update .repos with.'
    required: true
  input:
    description: 'Input .repos file.'
    required: true
  output:
    description: 'Output .repos file.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Update .repos
      id: repos-dep-update
      shell: bash
      env:
        GH_REPO: ${{ github.repository }}
        GH_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail

        branch="${{ inputs.branch }}"

        tmp_output=$(mktemp)
        trap 'rm -f "$tmp_output"' EXIT

        cp "${{ inputs.input }}" "$tmp_output"

        for repo in $(yq -r '.repositories | to_entries[] | .key' "${{ inputs.input }}"); do

          url=$(yq -r ".repositories.\"$repo\".url" "${{ inputs.input }}")
          info=$(git ls-remote "$url")

          if [[ $info == *"$branch"* ]]; then
            yq -yi ".repositories.\"$repo\".version = \"$branch\"" "$tmp_output"
          fi
        done

        mv "$tmp_output" "${{ inputs.output }}"
